### ISSUE TITLE
Arduino library

### ISSUE THREAD

**Issue by grgurpav** [DanielMartensson/Easy-CANopen#1]
How do I make this work with arduino? I can't import it as a library and if I could there are no examples of code so is my only option to reverse engineer your code?

**Comment by DanielMartensson** [comment]
> How do I make this work with arduino? I can't import it as a library and if I could there are no examples of code so is my only option to reverse engineer your code?

I haven't finish this library yet. I'm still working on it.

Use [Easy_CANopen_Other_Node.c](https://github.com/DanielMartensson/Easy-CANopen/blob/main/src/Easy_CANopen/Easy_CANopen_Other_Node.c) if you want to talk to other Nodes.

Use [Easy_CANopen_This_Node.c](https://github.com/DanielMartensson/Easy-CANopen/blob/main/src/Easy_CANopen/Easy_CANopen_This_Node.c) if you want to configure your Node.

Use [Easy_CANopen_Thread.c](https://github.com/DanielMartensson/Easy-CANopen/blob/main/src/Easy_CANopen/Easy_CANopen_Thread.c) if you want to listen for messages or send messages in a periodic time.
