### ISSUE TITLE
Does it allow me to have more than one slave node, i have a project with 6 of them 

### ISSUE THREAD

**Issue by Fatnorr** [DanielMartensson/Easy-CANopen#5]

**Comment by Fatnorr** [comment]
Does it allow me to have more than one slave node, i have a project with 6 of them, at the moment im using an arduino due

**Comment by DanielMartensson** [comment]
> Does it allow me to have more than one slave node, i have a project with 6 of them, at the moment im using an arduino due

@Fatnorr  You can have multiple slave nodes. This will work on Arduino.

Hmm...I think I need to add callbacks. It will be much easier to use then.
